### ISSUE TITLE
Recursive load from S3

### ISSUE THREAD

**Issue by mludvig** [githublemming/CloudTrailViewer#1]
Hi is it possible to load the CloudTrail logs from S3 recursively? Ie I would give CloudTrailViewer just the path to /AWSLogs/{account-id}/CloudTrail/ and it would walk and download the tree. 

As a bonus it could understand a date constraint from-to, e.g. only download from folders newer than 2016-01-01 or only between 2015-12-01 and 2015-12-31, and in that range include all regions or just some.

With that it should also be easy to implement "Refresh" - download and display any new log files that popped up in the folders.

Other than that I'm really enjoying the tool, keep up the good work! :)

**Comment by haskins-io** [comment]
Hi Michael,

I'm glad you find the application useful.

Loading a folder from S3 is doable, so is recursively loading child folders and files, though I do have a couple of concerns.

My first concern would be the performance in identifying all the files if the top level CloudTail was selected. Using a simple test harness it took over 6 seconds to find all the files for this month, for a single region. The SDK will only return a 1000 files at a time and then subsequent calls are needed to get the missing files which can be time consuming.

As an example loading from _/CloudTrail/_ it would have to handle:
- 9 regions
- x years
- 12 months per year
- 28/30/31 days per month
- 288 (at least) logs files per day

Another concern I have is memory usage; the application as it stands can experience issues loading over a 100 log files, (though that is dependant on how busy your AWS account is), so trying to load a couple of days or months would probably cause the application to grind to a halt and crash.

Adding a date constraint to the process should help to alleviate some of the issues with discovering the files, though there would still be the issue of loading complete files into memory.

I could see functionality like this being used for 'Scanning' events, I had already thought about this, though I was thinking of a single folder with no child folder recursion.

Prompting when new files are available is again something that I was thinking about, though again only dealing with a single folder.

Let me have a think about how this functionality could be implement and I'll see what I can do.

Mark

**Comment by haskins-io** [comment]
I've added the functionality so that you can select a S3 folder when performing a 'Scan' operation. This is just in the 'code' at the moment, so if you are running the application from source do a pull. I'll look to do a release in the next couple of days.

I'm looking into better filtering when loading files.

Mark

**Comment by haskins-io** [comment]
I've updated the S3FileChooser so when you are performing a 'Scan' operation the dialog provides a more advanced filtering functionality.

Simply select the type of filter that you want  (you can add more than one if required) and the filters will be applied against all loaded Events. You can either use the filters in AND mode or OR mode.

Currently you can only type one value into the fields e.g eu-west1  but I'm going to look to implement a means of entering multiple values separated by a delimiter e.g eu-west-1|eu-central-1

The new functionality is only available in code at the moment as I want to do UI improvements before adding the work to a release. Though talking of releases, the ability to select a folder as mentioned in the last comment was included in the latest release v2.6.0

**Comment by mludvig** [comment]
Thanks that works nicely! Indeed it eats quite a lot of memory - maybe if the Scan could immediately discard events like Describe\* / List\* / Get\* etc (ie non-security and non-resource) perhaps by way of some checkbox it could significantly reduce the size of imported data set?

**Comment by haskins-io** [comment]
Glad it worked. I have noticed that the memory footprint has reduced since I changed the way the files are loaded but I haven't done any profiling against that yet.

I'm still working on the Scan Filter Panel so I'll look to see what I can do with that in a way that it's customisable per user.

I'm going to close this as that is a separate task.
