### ISSUE TITLE
Export Functionality

### ISSUE THREAD

**Issue by fishermavis** [githublemming/CloudTrailViewer#10]
Hi I didn't really no where else I could send this, love the tool, is there any way a 'csv'/'tsv' export function could be added please.

Thank you for the brilliant tool, very useful

**Comment by haskins-io** [comment]
That shouldn't be a problem. I'll add a button to the main table at the bottom of the application so that it exports whatever is in the table.

I'm going to be away for a couple of weeks, so I won't be able to get this done much before the middle of Dec.

Mark

**Comment by haskins-io** [comment]
Sorry it's taken a while for this but you can now export whatever is in the table as a CSV file
