### ISSUE TITLE
Limit to number of log files available in a bucket prefix?

### ISSUE THREAD

**Issue by Dogers** [githublemming/CloudTrailViewer#16]
Our logs in S3 are broken down by account/region/year/month/day - when selecting a day in some (presumably busier) accounts, I'm only able to view and select files produced up to around 14:30.

Is there a limit to the number of files/pages of files returned somewhere?

**Comment by haskins-io** [comment]
There are no limits within the code.

If you are trying to load a whole day(s) worth of files, and you have a busy account, then you will most likely run into memory issues as the data is loaded into memory. 

If this is the case you could try using the scan feature and only load files / events that match a criteria.

**Comment by Dogers** [comment]
No, sorry, it's not stopping on the process of loading the files into the program, it's the _list_ of available files that appears to be truncated in the S3 browser, just prior to loading them in.

**Comment by haskins-io** [comment]
Ah, this looks like a pagination bug. I've done a quick fix and pushed it to the repo.

If you can run from source can you check this works. If not I'll look to create a binary release tomorrow.

**Comment by haskins-io** [comment]
Created a binary release with fix [3.1.2](https://github.com/githublemming/CloudTrailViewer/releases/tag/3.1.2).

Let me know if this solves your problem

**Comment by Dogers** [comment]
Unfortunately this version appears to just hang when opening a large prefix/folder :(

**Comment by haskins-io** [comment]
OK. Let me have another look at this

**Comment by haskins-io** [comment]
Hopefully this release [3.1.3](https://github.com/githublemming/CloudTrailViewer/releases/tag/3.1.3) should resolve that issue

**Comment by Dogers** [comment]
Looks good to me, thanks!
