### ISSUE TITLE
Small typo in the example security policy

### ISSUE THREAD

**Issue by jinesh-choksi** [githublemming/CloudTrailViewer#3]
There should be no trailing comma on the line: `"Resource": "arn:aws:s3:::cloudtrail-log*",`

i.e. should be: `"Resource": "arn:aws:s3:::cloudtrail-log*"`

and not: `"Resource": "arn:aws:s3:::cloudtrail-log*",`

**Comment by haskins-io** [comment]
Hi there,

thanks for pointing that out. I've corrected it.

Regards,

Mark
