### ISSUE TITLE
No build file or instructions

### ISSUE THREAD

**Issue by tomchiverton** [githublemming/CloudTrailViewer#6]

**Comment by haskins-io** [comment]
Hi Tom,

Yeah sorry about that. My hard disk was about to die, so I uploaded the code to GitHub before I lost it.

There is some information in the README_v2.md file about getting the application compiling and running via an IDE. It's a standard maven application so should be able to use commands like  mvn package  etc.

I'm hoping to get some time over the weekend to produce some basic documentation. There are some features that need to be added, and well as bugs to be squashed before I will create the initial preview release.

If you need a working version then download the latest v2 from releases.

Mark
