### ISSUE TITLE
Unable to add AWS accounts in preferance

### ISSUE THREAD

**Issue by robh007** [githublemming/CloudTrailViewer#7]
Hi,

Firstly great tool. In version 3 I don't appear to be able to see any AWS Accounts under preferences. I'm able to input text in a column but when you move to the next column the previous text disappears. Nothing saves either.

Rob.

**Comment by robh007** [comment]
Also I'm running the latest released version you have published.

**Comment by haskins-io** [comment]
Hi,

I was aware of that. It looks to be a 'feature' of the JavaFx editable table. What you need to do is enter a value into a cell then press 'enter' for the value to be accepted.

It's on my list of things to improve, when I find the time.

Glad you find it useful.

Mark

**Comment by robh007** [comment]
Yes - that works fine.
